import { randomUUID } from "node:crypto";
import { access, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it, vi } from "vitest";

import { JsonFileConfigProvider, configuredProvider, EnvironmentConfigProvider } from "../src/config-provider.js";
import type { ForwardRule } from "../src/bridge/forward-rule-matcher.js";
import { PlatformConfigProvider } from "../src/platform-config-provider.js";
import { EncryptedIngressQueue, type RuleForwardMessage } from "../src/platform-ingress.js";

const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((path) => rm(path, { recursive: true, force: true })));
});

describe("JsonFileConfigProvider", () => {
  it("loads the runtime configuration generated by AL-1S", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-bot-config-"));
    temporaryDirectories.push(directory);
    const path = join(directory, "discord-runtime.json");
    await writeFile(path, JSON.stringify({
      DISCORD_TOKEN: "test-discord-token-that-is-long-enough-for-validation",
      DISCORD_APPLICATION_ID: "1439231483326894160",
      DISCORD_OWNER_USER_IDS: "577928624884154368",
      DISCORD_GUILD_IDS: "1439045928785940598",
      DISCORD_CHANNEL_IDS: "",
      DISCORD_GROUP_CHANNEL_IDS: "1267070732735741972",
      QQ_TARGET_USER_ID: "123456789",
      QQ_TARGET_GROUP_ID: "704440930",
      ONEBOT_BASE_URL: "http://llbot:3000",
      ONEBOT_ACCESS_TOKEN: "al1s-managed-onebot-token"
    }), "utf8");

    const config = await new JsonFileConfigProvider(path).load();

    expect(config.discord.applicationId).toBe("1439231483326894160");
    expect(config).not.toHaveProperty("oneBot");
  });

  it("keeps environment configuration as the local-development fallback", () => {
    expect(configuredProvider({})).toBeInstanceOf(EnvironmentConfigProvider);
    expect(configuredProvider({ BOT_RUNTIME_CONFIG_PATH: "/runtime/bot.json" }))
      .toBeInstanceOf(JsonFileConfigProvider);
  });

  it("selects the authenticated platform provider without a shared platform file", () => {
    expect(configuredProvider({
      AL1S_CONTROL_BASE_URL: "http://platform:8000",
      AL1S_BOT_CREDENTIAL_PATH: "/run/secrets/bot-credential"
    })).toBeInstanceOf(PlatformConfigProvider);
  });
});

describe("PlatformConfigProvider", () => {
  it("propagates startup cancellation into the pending first rules request", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-bot-rules-abort-"));
    temporaryDirectories.push(directory);
    const credentialPath = join(directory, "credential");
    await writeFile(credentialPath, "worker-id.worker-secret", "utf8");
    let requestSignal: AbortSignal | undefined;
    const fetcher = vi.fn((_url: string | URL | Request, init?: RequestInit) => new Promise<Response>((_resolve, reject) => {
      requestSignal = init?.signal ?? undefined;
      requestSignal?.addEventListener("abort", () => reject(requestSignal?.reason), { once: true });
    }));
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000", credentialPath, stateDirectory: directory,
      fetcher: fetcher as typeof fetch,
    });
    const stop = new AbortController();
    const pending = provider.loadForwardRules(stop.signal);
    const rejected = expect(pending).rejects.toThrow("stopped");
    await vi.waitFor(() => expect(fetcher).toHaveBeenCalledOnce());
    stop.abort(new Error("stopped"));
    await rejected;
    expect(requestSignal?.aborted).toBe(true);
    await provider.close();
  });
  it("does not fetch rules when startup was cancelled during credential loading", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-bot-rules-stopped-"));
    temporaryDirectories.push(directory);
    const credentialPath = join(directory, "credential");
    await writeFile(credentialPath, "worker-id.worker-secret", "utf8");
    const fetcher = vi.fn(async () => Response.json({ items: [] }));
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000", credentialPath, stateDirectory: directory,
      fetcher: fetcher as typeof fetch,
    });
    const stop = new AbortController();
    const pending = provider.loadForwardRules(stop.signal);
    stop.abort(new Error("stopped"));
    await expect(pending).rejects.toThrow("stopped");
    expect(fetcher).not.toHaveBeenCalled();
    await provider.close();
  });
  it("reports bounded ingress failure and recovery without message content", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-bot-ingress-health-"));
    temporaryDirectories.push(directory);
    const credentialPath = join(directory, "credential");
    await writeFile(credentialPath, "worker-id.worker-secret", "utf8");
    const heartbeats: Array<Record<string, unknown>> = [];
    let accepting = false;
    const fetcher = vi.fn(async (input: string | URL | Request, init?: RequestInit) => {
      const url = String(input);
      if (url.endsWith("/rule-matches")) {
        return accepting
          ? Response.json({ id: randomUUID(), state: "received" }, { status: 202 })
          : new Response("", { status: 503 });
      }
      if (url.endsWith("/heartbeat")) {
        heartbeats.push(JSON.parse(String(init?.body)) as Record<string, unknown>);
      }
      return Response.json({});
    });
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000", credentialPath, stateDirectory: directory,
      fetcher: fetcher as unknown as typeof fetch,
    });
    const message: RuleForwardMessage = {
      kind: "rule_match", event_id: randomUUID(), rule_id: randomUUID(), rule_version: 1,
      guild_id: "123456789012345678", channel_id: "223456789012345678",
      message_ids: ["323456789012345678"], body: "private message text",
    };
    await provider.submitMessage(message);
    let stopIngress = provider.startIngress();
    try {
      await vi.waitFor(() => expect(fetcher.mock.calls.some(([url]) => String(url).endsWith("/rule-matches"))).toBe(true));
      let stopHeartbeat = provider.startHeartbeat(() => ({ status: "healthy", diagnostics: {} }));
      await vi.waitFor(() => expect(heartbeats.length).toBe(1));
      stopHeartbeat();
      expect(heartbeats[0]?.status).toBe("degraded");
      expect(heartbeats[0]?.diagnostics).toMatchObject({
        ingress_pending: 1, ingress_failure_count: 1,
        ingress_last_error_code: "upstream_unavailable",
      });
      expect(JSON.stringify(heartbeats[0])).not.toContain(message.body);
      expect(JSON.stringify(heartbeats[0])).not.toContain("worker-secret");

      stopIngress();
      accepting = true;
      stopIngress = provider.startIngress();
      await vi.waitFor(async () => {
        const queue = await EncryptedIngressQueue.open(directory);
        try { expect(queue.stats().ingress_pending).toBe(0); }
        finally { queue.close(); }
      });
      stopHeartbeat = provider.startHeartbeat(() => ({ status: "healthy", diagnostics: {} }));
      await vi.waitFor(() => expect(heartbeats.length).toBe(2));
      stopHeartbeat();
      expect(heartbeats[1]?.status).toBe("healthy");
      expect(heartbeats[1]?.diagnostics).toMatchObject({
        ingress_failure_count: 0, ingress_last_error_code: null,
        ingress_last_success_at: expect.any(String),
      });
    } finally {
      stopIngress();
      await provider.close();
    }
  });

  it("retries a failed queue open and shares the successful queue", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-bot-ingress-retry-"));
    temporaryDirectories.push(directory);
    const originalOpen = EncryptedIngressQueue.open.bind(EncryptedIngressQueue);
    const open = vi.spyOn(EncryptedIngressQueue, "open")
      .mockRejectedValueOnce(new Error("temporary storage failure"))
      .mockImplementation(originalOpen);
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000", credentialPath: "unused", stateDirectory: directory,
    });
    const message: RuleForwardMessage = {
      kind: "rule_match", event_id: randomUUID(), rule_id: randomUUID(), rule_version: 1,
      guild_id: "123456789012345678", channel_id: "223456789012345678",
      message_ids: ["323456789012345678"], body: "test message",
    };
    try {
      await expect(provider.submitMessage(message)).rejects.toThrow("temporary storage failure");
      await Promise.all([provider.submitMessage(message), provider.submitMessage(message)]);
      expect(open).toHaveBeenCalledTimes(2);
      await provider.close();
      const reopened = await originalOpen(directory);
      try {
        expect(reopened.stats().ingress_pending).toBe(1);
      } finally {
        reopened.close();
      }
    } finally {
      await provider.close();
      open.mockRestore();
    }
  });

  it("retains the last rule snapshot across a temporary fetch failure", async () => {
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000", credentialPath: "unused",
      stateDirectory: "unused", pollIntervalMs: 100,
    });
    const rule: ForwardRule = {
      id: randomUUID(), version: 1,
      guildId: "123456789012345678", channelId: "223456789012345678",
      trigger: { kind: "contains", text: "word" },
    };
    vi.spyOn(provider, "loadForwardRules")
      .mockResolvedValueOnce([rule])
      .mockRejectedValueOnce(new Error("platform unavailable"))
      .mockResolvedValueOnce([]);
    const onChange = vi.fn();
    vi.useFakeTimers();
    const stop = provider.watchForwardRules(onChange);
    try {
      await vi.advanceTimersByTimeAsync(0);
      expect(onChange.mock.calls).toEqual([[[rule]]]);
      await vi.advanceTimersByTimeAsync(100);
      expect(onChange.mock.calls).toEqual([[[rule]]]);
      await vi.advanceTimersByTimeAsync(100);
      expect(onChange.mock.calls).toEqual([[[rule]], [[]]]);
    } finally {
      stop();
      vi.useRealTimers();
    }
  });

  it("accepts bounded forwarding triggers and rejects malformed worker snapshots", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-rule-snapshot-"));
    temporaryDirectories.push(directory);
    await writeFile(join(directory, "credential"), "worker-id.worker-secret", "utf8");
    let count: number | null = 6;
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000", credentialPath: join(directory, "credential"),
      stateDirectory: directory,
      fetcher: vi.fn(async () => Response.json({ items: [{
        id: randomUUID(), row_version: 1,
        guild_id: "123456789012345678", channel_id: "223456789012345678",
        trigger_kind: "frequency", trigger_text: null,
        frequency_count: count, frequency_window_seconds: 10, cooldown_seconds: 10,
      }] })) as unknown as typeof fetch,
    });
    expect((await provider.loadForwardRules())[0]?.trigger).toEqual({
      kind: "frequency", count: 6, windowSeconds: 10, cooldownSeconds: 10,
    });
    count = null;
    await expect(provider.loadForwardRules()).rejects.toThrow();
  });

  it("accepts an identity-only candidate without inheriting forwarding rules", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-bot-identity-"));
    temporaryDirectories.push(directory);
    const candidate = platformCandidate();
    candidate.settings = { DISCORD_APPLICATION_ID: candidate.settings.DISCORD_APPLICATION_ID! };
    candidate.onebot_service_id = null;
    candidate.linked_onebot = null;
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000",
      credentialPath: join(directory, "credential"),
      stateDirectory: directory,
      fetcher: vi.fn(async () => Response.json(candidate)) as unknown as typeof fetch,
      environment: {
        DISCORD_OWNER_USER_IDS: "577928624884154368",
        DISCORD_GUILD_IDS: "1439045928785940598",
      },
    });
    await writeFile(join(directory, "credential"), "identity-id.secret\n", "utf8");
    const config = await provider.load();
    expect(config.discord).not.toHaveProperty("ownerUserIds");
    expect(config.discord).not.toHaveProperty("guildIds");
  });
  it("consumes a one-time registration code when the independent volume has no credential", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-bot-register-"));
    temporaryDirectories.push(directory);
    const credentialPath = join(directory, "credential");
    const registrationCodePath = join(directory, "registration-code");
    await writeFile(registrationCodePath, "grant-id.one-time-secret\n", "utf8");
    const candidate = platformCandidate();
    const fetcher = vi.fn(async (input: string | URL | Request, init?: RequestInit) => {
      const url = String(input);
      if (url.endsWith("/workers/register")) {
        expect(String(init?.body)).toContain("grant-id.one-time-secret");
        return Response.json({
          identity_id: randomUUID(),
          service_id: candidate.service_id,
          credential: "identity-id.long-term-secret"
        }, { status: 201 });
      }
      expect((init?.headers as Record<string, string>).Authorization)
        .toBe("Bearer identity-id.long-term-secret");
      return Response.json(candidate);
    }) as unknown as typeof fetch;
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000",
      credentialPath,
      registrationCodePath,
      stateDirectory: directory,
      fetcher,
      environment: {}
    });

    const config = await provider.load();
    expect(config.discord.applicationId).toBe("1439231483326894160");
    expect(config).not.toHaveProperty("oneBot");
    expect(await readFile(credentialPath, "utf8")).toBe("identity-id.long-term-secret\n");
    await expect(access(registrationCodePath)).rejects.toThrow();
    expect(fetcher).toHaveBeenCalledTimes(2);
  });

  it("promotes a validated candidate atomically and reuses it while the platform is offline", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-bot-state-"));
    temporaryDirectories.push(directory);
    const credentialPath = join(directory, "credential");
    await writeFile(credentialPath, "worker-id.worker-secret\n", "utf8");
    const candidate = platformCandidate();
    const requests: Array<{ url: string; init?: RequestInit }> = [];
    const fetcher = vi.fn(async (input: string | URL | Request, init?: RequestInit) => {
      requests.push({ url: String(input), ...(init === undefined ? {} : { init }) });
      if (String(input).endsWith("/config")) {
        return Response.json(candidate);
      }
      return Response.json({ status: "applied" });
    }) as unknown as typeof fetch;
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000/",
      credentialPath,
      stateDirectory: directory,
      fetcher,
      environment: { HOSTNAME: "worker-test" }
    });

    const config = await provider.load();
    expect(config.discord.applicationId).toBe("1439231483326894160");
    await expect(readFile(join(directory, "last-known-good.json"), "utf8")).rejects.toThrow();

    await provider.markApplied();
    const persisted = await readFile(join(directory, "last-known-good.json"), "utf8");
    expect(JSON.parse(persisted).config_version_id).toBe(candidate.config_version_id);
    expect(requests[1]?.init?.body).toContain('"status":"applied"');
    expect((requests[0]?.init?.headers as Record<string, string>).Authorization)
      .toBe("Bearer worker-id.worker-secret");
    const stopHeartbeat = provider.startHeartbeat(() => ({
      status: "healthy",
      diagnostics: { discord_ready: true }
    }));
    await vi.waitFor(() => {
      expect(requests.some((request) => request.url.endsWith("/worker/heartbeat"))).toBe(true);
    });
    stopHeartbeat();
    const heartbeat = requests.find((request) => request.url.endsWith("/worker/heartbeat"));
    expect(heartbeat?.init?.body).toContain(candidate.config_version_id);
    expect(heartbeat?.init?.body).not.toContain(String(candidate.secret));

    const offline = new PlatformConfigProvider({
      baseUrl: "http://platform:8000",
      credentialPath,
      stateDirectory: directory,
      fetcher: vi.fn(async () => { throw new Error("offline"); }) as unknown as typeof fetch,
      environment: {}
    });
    expect((await offline.load()).discord.applicationId).toBe("1439231483326894160");
  });

  it("rejects an invalid candidate without replacing the last-known-good file", async () => {
    const directory = await mkdtemp(join(tmpdir(), "al1s-bot-reject-"));
    temporaryDirectories.push(directory);
    const credentialPath = join(directory, "credential");
    await writeFile(credentialPath, "worker-id.worker-secret", "utf8");
    const valid = platformCandidate();
    const seedFetch = vi.fn(async (input: string | URL | Request) => (
      String(input).endsWith("/config") ? Response.json(valid) : Response.json({})
    )) as unknown as typeof fetch;
    const seed = new PlatformConfigProvider({
      baseUrl: "http://platform:8000",
      credentialPath,
      stateDirectory: directory,
      fetcher: seedFetch,
      environment: {}
    });
    await seed.load();
    await seed.markApplied();

    const invalid = { ...platformCandidate(), secret: "short" };
    const resultBodies: string[] = [];
    const rejectingFetch = vi.fn(async (input: string | URL | Request, init?: RequestInit) => {
      if (String(input).endsWith("/config")) {
        return Response.json(invalid);
      }
      resultBodies.push(String(init?.body));
      return Response.json({ status: "rejected" });
    }) as unknown as typeof fetch;
    const provider = new PlatformConfigProvider({
      baseUrl: "http://platform:8000",
      credentialPath,
      stateDirectory: directory,
      fetcher: rejectingFetch,
      environment: {}
    });

    const recovered = await provider.load();
    expect(recovered.discord.applicationId).toBe(valid.settings.DISCORD_APPLICATION_ID);
    expect(resultBodies).toHaveLength(1);
    expect(resultBodies[0]).toContain('"status":"rejected"');
    expect(resultBodies[0]).not.toContain("short");
  });
});

function platformCandidate(): Record<string, unknown> & {
  config_version_id: string;
  service_id: string;
  settings: Record<string, string>;
} {
  const oneBotServiceId = randomUUID();
  return {
    application_id: randomUUID(),
    application_row_version: 1,
    config_version_id: randomUUID(),
    version_no: 1,
    service_id: randomUUID(),
    settings: {
      DISCORD_APPLICATION_ID: "1439231483326894160",
      DISCORD_OWNER_USER_IDS: "577928624884154368",
      DISCORD_GUILD_IDS: "1439045928785940598",
      DISCORD_CHANNEL_IDS: "",
      DISCORD_GROUP_CHANNEL_IDS: "",
      QQ_TARGET_USER_ID: "123456789",
      QQ_TARGET_GROUP_ID: ""
    },
    secret: "test-discord-token-that-is-long-enough-for-validation",
    onebot_service_id: oneBotServiceId,
    linked_onebot: {
      service_id: oneBotServiceId,
      config_version_id: randomUUID(),
      settings: { ONEBOT_BASE_URL: "http://llbot:3000" },
      secret: "al1s-managed-onebot-token"
    },
    config_hash: "a".repeat(64)
  };
}
