from collections.abc import Callable
from typing import Any, Protocol
from uuid import UUID


class LineupRepositoryPort(Protocol):
    def create(self, **values: Any) -> UUID: ...
    def get(self, record_id: UUID) -> dict[str, Any]: ...
    def get_many(self, record_ids: list[UUID]) -> list[dict[str, Any]]: ...
    def occurrence_records(self, ids: list[UUID]) -> list[dict[str, Any]]: ...
    def page(self, cursor: UUID | None) -> list[dict[str, Any]]: ...
    def enrich(self, records: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
    def terminals(self) -> list[dict[str, Any]]: ...
    def attach_task(self, record_id: UUID, task_id: UUID, terminal_id: UUID) -> None: ...
    def save_review(self, record_id: UUID, version: int, ids: list[int | None]) -> None: ...


class LineupBatchCommandsPort(Protocol):
    def create(
        self,
        ids: list[UUID],
        terminal_id: UUID,
        options: dict[str, Any],
        key: str,
        *,
        retry_source: UUID | None = None,
        validate_terminal: Callable[[], None] | None = None,
    ) -> UUID: ...


class LineupWorkspaceQueriesPort(Protocol):
    def task(self, task_id: UUID, *, after: int = 0, category: str = "all") -> dict[str, Any]: ...
    def annotation_tasks(self, before: UUID | None = None) -> dict[str, Any]: ...


class LineupAnnotationRepositoryPort(Protocol):
    def save(self, record_id: UUID, version: int, payload: dict[str, Any]) -> dict[str, Any]: ...
